### ISSUE TITLE
The case code you provided is not running

### ISSUE THREAD

**Issue by QifengOu** [AFBuratin/circIMPACT#1]
There seems to be a problem with these two functions:
circIMPACT <- circIMPACT::marker.selection(dat = circNormDeseq, 
                               dds = dds.filt.expr, 
                               sf = sf.filt, p.cutoff = 0.05, lfc.cutoff = 1)

circIMPACT_Kmeans <- marker.selection(dat = circNormDeseq,
                                      dds = dds.filt.expr,
                                      sf = sf.filt, p.cutoff = 0.05, lfc.cutoff = NULL, 
                                      method.d = "euclidean", method.c = "ward.D2",
                                      median = FALSE, choose.k = TRUE, index.m = "silhouette")

**Comment by QifengOu** [comment]
> circIMPACT_Kmeans <- marker.selection(dat = circNormDeseq,
+                                       dds = dds.filt.expr,
+                                       sf = sf.filt, p.cutoff = 0.05, lfc.cutoff = NULL, 
+                                       method.d = "euclidean", method.c = "ward.D2",
+                                       median = FALSE, choose.k = TRUE, index.m = "silhouette")
Error in get(s, env, inherits = FALSE) : 缺少参数"k",也没有缺省值
> circIMPACT_Kmeans <- marker.selection(dat = circNormDeseq,
+                                       dds = dds.filt.expr,k = 2,
+                                       sf = sf.filt, p.cutoff = 0.05, lfc.cutoff = NULL, 
+                                       method.d = "euclidean", method.c = "ward.D2",
+                                       median = FALSE, choose.k = TRUE, index.m = "silhouette")
Error in { : task 1 failed - "'x'必需为数值"
> circIMPACT <- circIMPACT::marker.selection(dat = circNormDeseq, 
+                                dds = dds.filt.expr, 
+                                sf = sf.filt, p.cutoff = 0.05, lfc.cutoff = 1)
Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  所有链结都已在运行
> circIMPACT_Kmeans <- marker.selection(dat = circNormDeseq,
+                                       dds = dds.filt.expr,k = 2,
+                                       sf = sf.filt, p.cutoff = 0.05, lfc.cutoff = NULL, 
+                                       method.d = "euclidean", method.c = "ward.D2",
+                                       median = FALSE, choose.k = TRUE, index.m = "silhouette")
Error in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  所有链结都已在运行
此外: Warning messages:
1: In .Internal(socketAccept(socket, blocking, open, encoding, timeout)) :
  关闭不再使用的链结125(<-DESKTOP-AHFAL06:11839)
2: In .Internal(socketAccept(socket, blocking, open, encoding, timeout)) :
  关闭不再使用的链结124(<-DESKTOP-AHFAL06:11839)
3: In .Internal(socketAccept(socket, blocking, open, encoding, timeout)) :
  关闭不再使用的链结123(<-DESKTOP-AHFAL06:11839)
4: In .Internal(socketAccept(socket, blocking, open, encoding, timeout)) :
  关闭不再使用的链结122(<-DESKTOP-AHFAL06:11839)
5: In .Internal(socketAccept(socket, blocking, open, encoding, timeout)) :
  关闭不再使用的链结121(<-DESKTOP-AHFAL06:11839)
6: In .Internal(socketAccept(socket, blocking, open, encoding, timeout)) :
  关闭不再使用的链结120(<-DESKTOP-AHFAL06:11839)
7: In .Internal(socketAccept(socket, blocking, open, encoding, timeout)) :
  关闭不再使用的链结119(<-DESKTOP-AHFAL06:11839)
8: In .Internal(socketAccept(socket, blocking, open, encoding, timeout)) :
  关闭不再使用的链结118(<-DESKTOP-AHFAL06:11839)

**Comment by gbnegrini** [comment]
Hello @QifengOu!
I had the same issue you reported. I have just submitted a pull request #2  with a possible solution.

**Comment by AFBuratin** [comment]
Hi @QifengOu !
I hope that the solution proposed by @gbnegrini can help you fix this issue !
Thanks all for the collaboration and enjoy with the CircIMPACT package ;) !!

**Comment by QifengOu** [comment]
> Hello @QifengOu!
> I had the same issue you reported. I have just submitted a pull request #2 with a possible solution.

Thank you very much!!  It is working now!!

**Comment by QifengOu** [comment]
> Hi @QifengOu !
> I hope that the solution proposed by @gbnegrini can help you fix this issue !
> Thanks all for the collaboration and enjoy with the CircIMPACT package ;) !!

yes,  thinks your package!! this package is very useful for me!
